# -*- coding: utf-8 -*-

def getColor(r,g,b):
    colors = ["white","black","gray",
              "blue","green","lightblue","brown",
              "purple","yello","red","pink","orange"]

    if r<=25 and g<=25 and b<=25:
        return 0
    elif r>=225 and g>=225 and b>=225:
        return 1
    else:
        if r<=45:
            if g<=45:
                if b<=45:
                    return 2
                elif 45<b<=80:
                    return 3
                elif 80<b<=115:
                    return 3
                elif 115<b<=150:
                    return 3
                elif 150<b<=185:
                    return 3
                elif 185<b<=220:
                    return 3
                else:
                    return 3
            elif 45<g<=80:
                if b<=45:
                    return 4
                elif 45<b<=80:
                    return 4
                elif 80<b<=115:
                    return 3
                elif 115<b<=150:
                    return 3
                elif 150<b<=185:
                    return 3
                elif 185<b<=220:
                    return 3
                else:
                    return 3
            elif 80<g<=115:
                if b<=45:
                    return 4
                elif 45<b<=80:
                    return 4
                elif 80<b<=115:
                    return 5
                elif 115<b<=150:
                    return 3
                elif 150<b<=185:
                    return 3
                elif 185<b<=220:
                    return 3
                else:
                    return 3
            elif 115<g<=150:
                if b<=45:
                    return 4
                elif 45<b<=80:
                    return 4
                elif 80<b<=115:
                    return 4
                elif 115<b<=150:
                    return 5
                elif 150<b<=185:
                    return 5
                elif 185<b<=220:
                    return 5
                else:
                    return 3
            elif 150<g<=185:
                if b<=45:
                    return 4
                elif 45<b<=80:
                    return 4
                elif 80<b<=115:
                    return 4
                elif 115<b<=150:
                    return 5
                elif 150<b<=185:
                    return 5
                elif 185<b<=220:
                    return 5
                else:
                    return 5
            elif 185<g<=220:
                if b<=45:
                    return 4
                elif 45<b<=80:
                    return 4
                elif 80<b<=115:
                    return 4
                elif 115<b<=150:
                    return 4
                elif 150<b<=185:
                    return 5
                elif 185<b<=220:
                    return 5
                else:
                    return 5
            else:
                if b<=45:
                    return 4
                elif 45<b<=80:
                    return 4
                elif 80<b<=115:
                    return 4
                elif 115<b<=150:
                    return 4
                elif 150<b<=185:
                    return 4
                elif 185<b<=220:
                    return 5
                else:
                    return 5
        elif 45<r<=80:
            if g<=45:
                if b<=45:
                    return 6
                elif 45<b<=80:
                    return 7
                elif 80<b<=115:
                    return 7
                elif 115<b<=150:
                    return 7
                elif 150<b<=185:
                    return 7
                elif 185<b<=220:
                    return 7
                else:
                    return 7
            elif 45<g<=80:
                if b<=45:
                    return 4
                elif 45<b<=80:
                    return 2
                elif 80<b<=115:
                    return 2
                elif 115<b<=150:
                    return 7
                elif 150<b<=185:
                    return 7
                elif 185<b<=220:
                    return 7
                else:
                    return 7
            elif 80<g<=115:
                if b<=45:
                    return 4
                elif 45<b<=80:
                    return 4
                elif 80<b<=115:
                    return 3
                elif 115<b<=150:
                    return 3
                elif 150<b<=185:
                    return 3
                elif 185<b<=220:
                    return 3
                else:
                    return 3
            elif 115<g<=150:
                if b<=45:
                    return 4
                elif 45<b<=80:
                    return 4
                elif 80<b<=115:
                    return 4
                elif 115<b<=150:
                    return 5
                elif 150<b<=185:
                    return 5
                elif 185<b<=220:
                    return 5
                else:
                    return 3
            elif 150<g<=185:
                if b<=45:
                    return 4
                elif 45<b<=80:
                    return 4
                elif 80<b<=115:
                    return 4
                elif 115<b<=150:
                    return 4
                elif 150<b<=185:
                    return 3
                elif 185<b<=220:
                    return 3
                else:
                    return 3
            elif 185<g<=220:
                if b<=45:
                    return 4
                elif 45<b<=80:
                    return 4
                elif 80<b<=115:
                    return 4
                elif 115<b<=150:
                    return 5
                elif 150<b<=185:
                    return 5
                elif 185<b<=220:
                    return 5
                else:
                    return 5
            else:
                if b<=45:
                    return 4
                elif 45<b<=80:
                    return 4
                elif 80<b<=115:
                    return 4
                elif 115<b<=150:
                    return 4
                elif 150<b<=185:
                    return 4
                elif 185<b<=220:
                    return 5
                else:
                    return 5
        elif 80<r<=115:
            if g<=45:
                if b<=45:
                    return 6
                elif 45<b<=80:
                    return 7
                elif 80<b<=115:
                    return 7
                elif 115<b<=150:
                    return 7
                elif 150<b<=185:
                    return 7
                elif 185<b<=220:
                    return 7
                else:
                    return 7
            elif 45<g<=80:
                if b<=45:
                    return 6
                elif 45<b<=80:
                    return 6
                elif 80<b<=115:
                    return 7
                elif 115<b<=150:
                    return 7
                elif 150<b<=185:
                    return 7
                elif 185<b<=220:
                    return 7
                else:
                    return 7
            elif 80<g<=115:
                if b<=45:
                    return 4
                elif 45<b<=80:
                    return 2
                elif 80<b<=115:
                    return 2
                elif 115<b<=150:
                    return 2
                elif 150<b<=185:
                    return 7
                elif 185<b<=220:
                    return 7
                else:
                    return 7
            elif 115<g<=150:
                if b<=45:
                    return 4
                elif 45<b<=80:
                    return 4
                elif 80<b<=115:
                    return 2
                elif 115<b<=150:
                    return 2
                elif 150<b<=185:
                    return 2
                elif 185<b<=220:
                    return 3
                else:
                    return 3
            elif 150<g<=185:
                if b<=45:
                    return 4
                elif 45<b<=80:
                    return 4
                elif 80<b<=115:
                    return 4
                elif 115<b<=150:
                    return 5
                elif 150<b<=185:
                    return 5
                elif 185<b<=220:
                    return 3
                else:
                    return 3
            elif 185<g<=220:
                if b<=45:
                    return 4
                elif 45<b<=80:
                    return 4
                elif 80<b<=115:
                    return 4
                elif 115<b<=150:
                    return 4
                elif 150<b<=185:
                    return 5
                elif 185<b<=220:
                    return 5
                else:
                    return 5
            else:
                if b<=45:
                    return 4
                elif 45<b<=80:
                    return 4
                elif 80<b<=115:
                    return 4
                elif 115<b<=150:
                    return 4
                elif 150<b<=185:
                    return 5
                elif 185<b<=220:
                    return 5
                else:
                    return 5
        elif 115<r<=150:
            if g<=45:
                if b<=45:
                    return 6
                elif 45<b<=80:
                    return 7
                elif 80<b<=115:
                    return 7
                elif 115<b<=150:
                    return 7
                elif 150<b<=185:
                    return 7
                elif 185<b<=220:
                    return 7
                else:
                    return 7
            elif 45<g<=80:
                if b<=45:
                    return 6
                elif 45<b<=80:
                    return 6
                elif 80<b<=115:
                    return 7
                elif 115<b<=150:
                    return 7
                elif 150<b<=185:
                    return 7
                elif 185<b<=220:
                    return 7
                else:
                    return 7
            elif 80<g<=115:
                if b<=45:
                    return 6
                elif 45<b<=80:
                    return 6
                elif 80<b<=115:
                    return 2
                elif 115<b<=150:
                    return 7
                elif 150<b<=185:
                    return 7
                elif 185<b<=220:
                    return 7
                else:
                    return 7
            elif 115<g<=150:
                if b<=45:
                    return 4
                elif 45<b<=80:
                    return 4
                elif 80<b<=115:
                    return 2
                elif 115<b<=150:
                    return 2
                elif 150<b<=185:
                    return 2
                elif 185<b<=220:
                    return 7
                else:
                    return 7
            elif 150<g<=185:
                if b<=45:
                    return 4
                elif 45<b<=80:
                    return 4
                elif 80<b<=115:
                    return 4
                elif 115<b<=150:
                    return 4
                elif 150<b<=185:
                    return 2
                elif 185<b<=220:
                    return 5
                else:
                    return 3
            elif 185<g<=220:
                if b<=45:
                    return 4
                elif 45<b<=80:
                    return 4
                elif 80<b<=115:
                    return 4
                elif 115<b<=150:
                    return 4
                elif 150<b<=185:
                    return 5
                elif 185<b<=220:
                    return 5
                else:
                    return 5
            else:
                if b<=45:
                    return 4
                elif 45<b<=80:
                    return 4
                elif 80<b<=115:
                    return 4
                elif 115<b<=150:
                    return 4
                elif 150<b<=185:
                    return 4
                elif 185<b<=220:
                    return 5
                else:
                    return 5
        elif 150<r<=185:
            if g<=45:
                if b<=45:
                    return 6
                elif 45<b<=80:
                    return 6
                elif 80<b<=115:
                    return 7
                elif 115<b<=150:
                    return 7
                elif 150<b<=185:
                    return 7
                elif 185<b<=220:
                    return 7
                else:
                    return 7
            elif 45<g<=80:
                if b<=45:
                    return 6
                elif 45<b<=80:
                    return 6
                elif 80<b<=115:
                    return 7
                elif 115<b<=150:
                    return 7
                elif 150<b<=185:
                    return 7
                elif 185<b<=220:
                    return 7
                else:
                    return 7
            elif 80<g<=115:
                if b<=45:
                    return 6
                elif 45<b<=80:
                    return 6
                elif 80<b<=115:
                    return 6
                elif 115<b<=150:
                    return 7
                elif 150<b<=185:
                    return 7
                elif 185<b<=220:
                    return 7
                else:
                    return 7
            elif 115<g<=150:
                if b<=45:
                    return 8
                elif 45<b<=80:
                    return 6
                elif 80<b<=115:
                    return 6
                elif 115<b<=150:
                    return 7
                elif 150<b<=185:
                    return 7
                elif 185<b<=220:
                    return 7
                else:
                    return 7
            elif 150<g<=185:
                if b<=45:
                    return 4
                elif 45<b<=80:
                    return 4
                elif 80<b<=115:
                    return 2
                elif 115<b<=150:
                    return 2
                elif 150<b<=185:
                    return 2
                elif 185<b<=220:
                    return 2
                else:
                    return 7
            elif 185<g<=220:
                if b<=45:
                    return 4
                elif 45<b<=80:
                    return 4
                elif 80<b<=115:
                    return 4
                elif 115<b<=150:
                    return 4
                elif 150<b<=185:
                    return 4
                elif 185<b<=220:
                    return 5
                else:
                    return 5
            else:
                if b<=45:
                    return 4
                elif 45<b<=80:
                    return 4
                elif 80<b<=115:
                    return 4
                elif 115<b<=150:
                    return 4
                elif 150<b<=185:
                    return 4
                elif 185<b<=220:
                    return 5
                else:
                    return 5
        elif 185<r<=220:
            if g<=45:
                if b<=45:
                    return 9
                elif 45<b<=80:
                    return 9
                elif 80<b<=115:
                    return 10
                elif 115<b<=150:
                    return 10
                elif 150<b<=185:
                    return 7
                elif 185<b<=220:
                    return 7
                else:
                    return 7
            elif 45<g<=80:
                if b<=45:
                    return 11
                elif 45<b<=80:
                    return 6
                elif 80<b<=115:
                    return 10
                elif 115<b<=150:
                    return 10
                elif 150<b<=185:
                    return 7
                elif 185<b<=220:
                    return 7
                else:
                    return 7
            elif 80<g<=115:
                if b<=45:
                    return 11
                elif 45<b<=80:
                    return 11
                elif 80<b<=115:
                    return 10
                elif 115<b<=150:
                    return 10
                elif 150<b<=185:
                    return 10
                elif 185<b<=220:
                    return 7
                else:
                    return 7
            elif 115<g<=150:
                if b<=45:
                    return 6
                elif 45<b<=80:
                    return 6
                elif 80<b<=115:
                    return 10
                elif 115<b<=150:
                    return 10
                elif 150<b<=185:
                    return 10
                elif 185<b<=220:
                    return 7
                else:
                    return 7
            elif 150<g<=185:
                if b<=45:
                    return 8
                elif 45<b<=80:
                    return 6
                elif 80<b<=115:
                    return 6
                elif 115<b<=150:
                    return 10
                elif 150<b<=185:
                    return 10
                elif 185<b<=220:
                    return 7
                else:
                    return 7
            elif 185<g<=220:
                if b<=45:
                    return 4
                elif 45<b<=80:
                    return 4
                elif 80<b<=115:
                    return 4
                elif 115<b<=150:
                    return 4
                elif 150<b<=185:
                    return 2
                elif 185<b<=220:
                    return 2
                else:
                    return 7
            else:
                if b<=45:
                    return 4
                elif 45<b<=80:
                    return 4
                elif 80<b<=115:
                    return 4
                elif 115<b<=150:
                    return 4
                elif 150<b<=185:
                    return 4
                elif 185<b<=220:
                    return 5
                else:
                    return 5
        else:
            if g<=45:
                if b<=45:
                    return 9
                elif 45<b<=80:
                    return 9
                elif 80<b<=115:
                    return 9
                elif 115<b<=150:
                    return 10
                elif 150<b<=185:
                    return 10
                elif 185<b<=220:
                    return 10
                else:
                    return 7
            elif 45<g<=80:
                if b<=45:
                    return 11
                elif 45<b<=80:
                    return 9
                elif 80<b<=115:
                    return 10
                elif 115<b<=150:
                    return 10
                elif 150<b<=185:
                    return 10
                elif 185<b<=220:
                    return 10
                else:
                    return 7
            elif 80<g<=115:
                if b<=45:
                    return 11
                elif 45<b<=80:
                    return 11
                elif 80<b<=115:
                    return 10
                elif 115<b<=150:
                    return 10
                elif 150<b<=185:
                    return 10
                elif 185<b<=220:
                    return 10
                else:
                    return 10
            elif 115<g<=150:
                if b<=45:
                    return 11
                elif 45<b<=80:
                    return 11
                elif 80<b<=115:
                    return 10
                elif 115<b<=150:
                    return 10
                elif 150<b<=185:
                    return 10
                elif 185<b<=220:
                    return 10
                else:
                    return 10
            elif 150<g<=185:
                if b<=45:
                    return 11
                elif 45<b<=80:
                    return 11
                elif 80<b<=115:
                    return 10
                elif 115<b<=150:
                    return 10
                elif 150<b<=185:
                    return 10
                elif 185<b<=220:
                    return 10
                else:
                    return 10
            elif 185<g<=220:
                if b<=45:
                    return 8
                elif 45<b<=80:
                    return 8
                elif 80<b<=115:
                    return 6
                elif 115<b<=150:
                    return 6
                elif 150<b<=185:
                    return 10
                elif 185<b<=220:
                    return 10
                else:
                    return 10
            else:
                if b<=45:
                    return 8
                elif 45<b<=80:
                    return 8
                elif 80<b<=115:
                    return 8
                elif 115<b<=150:
                    return 8
                elif 150<b<=185:
                    return 8
                elif 185<b<=220:
                    return 0
                else:
                    return 0
